// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hospital.proto

package proto;

public final class HospitalOuterClass {
  private HospitalOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code proto.Empty}
   */
  public  static final class Empty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Empty)
      EmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empty() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Empty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.HospitalOuterClass.internal_static_proto_Empty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.HospitalOuterClass.internal_static_proto_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.HospitalOuterClass.Empty.class, proto.HospitalOuterClass.Empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.HospitalOuterClass.Empty)) {
        return super.equals(obj);
      }
      proto.HospitalOuterClass.Empty other = (proto.HospitalOuterClass.Empty) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.HospitalOuterClass.Empty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HospitalOuterClass.Empty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HospitalOuterClass.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HospitalOuterClass.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HospitalOuterClass.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HospitalOuterClass.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HospitalOuterClass.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.HospitalOuterClass.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.HospitalOuterClass.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.HospitalOuterClass.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.HospitalOuterClass.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.HospitalOuterClass.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.HospitalOuterClass.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Empty)
        proto.HospitalOuterClass.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.HospitalOuterClass.internal_static_proto_Empty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.HospitalOuterClass.internal_static_proto_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.HospitalOuterClass.Empty.class, proto.HospitalOuterClass.Empty.Builder.class);
      }

      // Construct using proto.HospitalOuterClass.Empty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.HospitalOuterClass.internal_static_proto_Empty_descriptor;
      }

      @java.lang.Override
      public proto.HospitalOuterClass.Empty getDefaultInstanceForType() {
        return proto.HospitalOuterClass.Empty.getDefaultInstance();
      }

      @java.lang.Override
      public proto.HospitalOuterClass.Empty build() {
        proto.HospitalOuterClass.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.HospitalOuterClass.Empty buildPartial() {
        proto.HospitalOuterClass.Empty result = new proto.HospitalOuterClass.Empty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.HospitalOuterClass.Empty) {
          return mergeFrom((proto.HospitalOuterClass.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.HospitalOuterClass.Empty other) {
        if (other == proto.HospitalOuterClass.Empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.HospitalOuterClass.Empty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.HospitalOuterClass.Empty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Empty)
    }

    // @@protoc_insertion_point(class_scope:proto.Empty)
    private static final proto.HospitalOuterClass.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.HospitalOuterClass.Empty();
    }

    public static proto.HospitalOuterClass.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Empty>
        PARSER = new com.google.protobuf.AbstractParser<Empty>() {
      @java.lang.Override
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Empty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.HospitalOuterClass.Empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AvailableBedsReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.AvailableBedsReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 message = 1;</code>
     */
    int getMessage();
  }
  /**
   * Protobuf type {@code proto.AvailableBedsReply}
   */
  public  static final class AvailableBedsReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.AvailableBedsReply)
      AvailableBedsReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AvailableBedsReply.newBuilder() to construct.
    private AvailableBedsReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AvailableBedsReply() {
      message_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AvailableBedsReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              message_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.HospitalOuterClass.internal_static_proto_AvailableBedsReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.HospitalOuterClass.internal_static_proto_AvailableBedsReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.HospitalOuterClass.AvailableBedsReply.class, proto.HospitalOuterClass.AvailableBedsReply.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private int message_;
    /**
     * <code>int32 message = 1;</code>
     */
    public int getMessage() {
      return message_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (message_ != 0) {
        output.writeInt32(1, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (message_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.HospitalOuterClass.AvailableBedsReply)) {
        return super.equals(obj);
      }
      proto.HospitalOuterClass.AvailableBedsReply other = (proto.HospitalOuterClass.AvailableBedsReply) obj;

      boolean result = true;
      result = result && (getMessage()
          == other.getMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.HospitalOuterClass.AvailableBedsReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HospitalOuterClass.AvailableBedsReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HospitalOuterClass.AvailableBedsReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HospitalOuterClass.AvailableBedsReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HospitalOuterClass.AvailableBedsReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HospitalOuterClass.AvailableBedsReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HospitalOuterClass.AvailableBedsReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.HospitalOuterClass.AvailableBedsReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.HospitalOuterClass.AvailableBedsReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.HospitalOuterClass.AvailableBedsReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.HospitalOuterClass.AvailableBedsReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.HospitalOuterClass.AvailableBedsReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.HospitalOuterClass.AvailableBedsReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.AvailableBedsReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.AvailableBedsReply)
        proto.HospitalOuterClass.AvailableBedsReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.HospitalOuterClass.internal_static_proto_AvailableBedsReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.HospitalOuterClass.internal_static_proto_AvailableBedsReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.HospitalOuterClass.AvailableBedsReply.class, proto.HospitalOuterClass.AvailableBedsReply.Builder.class);
      }

      // Construct using proto.HospitalOuterClass.AvailableBedsReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        message_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.HospitalOuterClass.internal_static_proto_AvailableBedsReply_descriptor;
      }

      @java.lang.Override
      public proto.HospitalOuterClass.AvailableBedsReply getDefaultInstanceForType() {
        return proto.HospitalOuterClass.AvailableBedsReply.getDefaultInstance();
      }

      @java.lang.Override
      public proto.HospitalOuterClass.AvailableBedsReply build() {
        proto.HospitalOuterClass.AvailableBedsReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.HospitalOuterClass.AvailableBedsReply buildPartial() {
        proto.HospitalOuterClass.AvailableBedsReply result = new proto.HospitalOuterClass.AvailableBedsReply(this);
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.HospitalOuterClass.AvailableBedsReply) {
          return mergeFrom((proto.HospitalOuterClass.AvailableBedsReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.HospitalOuterClass.AvailableBedsReply other) {
        if (other == proto.HospitalOuterClass.AvailableBedsReply.getDefaultInstance()) return this;
        if (other.getMessage() != 0) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.HospitalOuterClass.AvailableBedsReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.HospitalOuterClass.AvailableBedsReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int message_ ;
      /**
       * <code>int32 message = 1;</code>
       */
      public int getMessage() {
        return message_;
      }
      /**
       * <code>int32 message = 1;</code>
       */
      public Builder setMessage(int value) {
        
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 message = 1;</code>
       */
      public Builder clearMessage() {
        
        message_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.AvailableBedsReply)
    }

    // @@protoc_insertion_point(class_scope:proto.AvailableBedsReply)
    private static final proto.HospitalOuterClass.AvailableBedsReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.HospitalOuterClass.AvailableBedsReply();
    }

    public static proto.HospitalOuterClass.AvailableBedsReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AvailableBedsReply>
        PARSER = new com.google.protobuf.AbstractParser<AvailableBedsReply>() {
      @java.lang.Override
      public AvailableBedsReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AvailableBedsReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AvailableBedsReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AvailableBedsReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.HospitalOuterClass.AvailableBedsReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HospitalOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Hospital)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 test = 1;</code>
     */
    int getTest();

    /**
     * <code>string host = 2;</code>
     */
    java.lang.String getHost();
    /**
     * <code>string host = 2;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <code>int32 port = 3;</code>
     */
    int getPort();

    /**
     * <code>int32 id = 4;</code>
     */
    int getId();

    /**
     * <code>string name = 5;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 5;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 totalBeds = 6;</code>
     */
    int getTotalBeds();

    /**
     * <code>int32 availableBeds = 7;</code>
     */
    int getAvailableBeds();
  }
  /**
   * Protobuf type {@code proto.Hospital}
   */
  public  static final class Hospital extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Hospital)
      HospitalOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Hospital.newBuilder() to construct.
    private Hospital(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Hospital() {
      test_ = 0;
      host_ = "";
      port_ = 0;
      id_ = 0;
      name_ = "";
      totalBeds_ = 0;
      availableBeds_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Hospital(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              test_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 24: {

              port_ = input.readInt32();
              break;
            }
            case 32: {

              id_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 48: {

              totalBeds_ = input.readInt32();
              break;
            }
            case 56: {

              availableBeds_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.HospitalOuterClass.internal_static_proto_Hospital_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.HospitalOuterClass.internal_static_proto_Hospital_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.HospitalOuterClass.Hospital.class, proto.HospitalOuterClass.Hospital.Builder.class);
    }

    public static final int TEST_FIELD_NUMBER = 1;
    private int test_;
    /**
     * <code>int32 test = 1;</code>
     */
    public int getTest() {
      return test_;
    }

    public static final int HOST_FIELD_NUMBER = 2;
    private volatile java.lang.Object host_;
    /**
     * <code>string host = 2;</code>
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <code>string host = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 3;
    private int port_;
    /**
     * <code>int32 port = 3;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int ID_FIELD_NUMBER = 4;
    private int id_;
    /**
     * <code>int32 id = 4;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 5;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOTALBEDS_FIELD_NUMBER = 6;
    private int totalBeds_;
    /**
     * <code>int32 totalBeds = 6;</code>
     */
    public int getTotalBeds() {
      return totalBeds_;
    }

    public static final int AVAILABLEBEDS_FIELD_NUMBER = 7;
    private int availableBeds_;
    /**
     * <code>int32 availableBeds = 7;</code>
     */
    public int getAvailableBeds() {
      return availableBeds_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (test_ != 0) {
        output.writeInt32(1, test_);
      }
      if (!getHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, host_);
      }
      if (port_ != 0) {
        output.writeInt32(3, port_);
      }
      if (id_ != 0) {
        output.writeInt32(4, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, name_);
      }
      if (totalBeds_ != 0) {
        output.writeInt32(6, totalBeds_);
      }
      if (availableBeds_ != 0) {
        output.writeInt32(7, availableBeds_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (test_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, test_);
      }
      if (!getHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, host_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, port_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, name_);
      }
      if (totalBeds_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, totalBeds_);
      }
      if (availableBeds_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, availableBeds_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.HospitalOuterClass.Hospital)) {
        return super.equals(obj);
      }
      proto.HospitalOuterClass.Hospital other = (proto.HospitalOuterClass.Hospital) obj;

      boolean result = true;
      result = result && (getTest()
          == other.getTest());
      result = result && getHost()
          .equals(other.getHost());
      result = result && (getPort()
          == other.getPort());
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && (getTotalBeds()
          == other.getTotalBeds());
      result = result && (getAvailableBeds()
          == other.getAvailableBeds());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEST_FIELD_NUMBER;
      hash = (53 * hash) + getTest();
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + TOTALBEDS_FIELD_NUMBER;
      hash = (53 * hash) + getTotalBeds();
      hash = (37 * hash) + AVAILABLEBEDS_FIELD_NUMBER;
      hash = (53 * hash) + getAvailableBeds();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.HospitalOuterClass.Hospital parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HospitalOuterClass.Hospital parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HospitalOuterClass.Hospital parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HospitalOuterClass.Hospital parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HospitalOuterClass.Hospital parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HospitalOuterClass.Hospital parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HospitalOuterClass.Hospital parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.HospitalOuterClass.Hospital parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.HospitalOuterClass.Hospital parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.HospitalOuterClass.Hospital parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.HospitalOuterClass.Hospital parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.HospitalOuterClass.Hospital parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.HospitalOuterClass.Hospital prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Hospital}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Hospital)
        proto.HospitalOuterClass.HospitalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.HospitalOuterClass.internal_static_proto_Hospital_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.HospitalOuterClass.internal_static_proto_Hospital_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.HospitalOuterClass.Hospital.class, proto.HospitalOuterClass.Hospital.Builder.class);
      }

      // Construct using proto.HospitalOuterClass.Hospital.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        test_ = 0;

        host_ = "";

        port_ = 0;

        id_ = 0;

        name_ = "";

        totalBeds_ = 0;

        availableBeds_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.HospitalOuterClass.internal_static_proto_Hospital_descriptor;
      }

      @java.lang.Override
      public proto.HospitalOuterClass.Hospital getDefaultInstanceForType() {
        return proto.HospitalOuterClass.Hospital.getDefaultInstance();
      }

      @java.lang.Override
      public proto.HospitalOuterClass.Hospital build() {
        proto.HospitalOuterClass.Hospital result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.HospitalOuterClass.Hospital buildPartial() {
        proto.HospitalOuterClass.Hospital result = new proto.HospitalOuterClass.Hospital(this);
        result.test_ = test_;
        result.host_ = host_;
        result.port_ = port_;
        result.id_ = id_;
        result.name_ = name_;
        result.totalBeds_ = totalBeds_;
        result.availableBeds_ = availableBeds_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.HospitalOuterClass.Hospital) {
          return mergeFrom((proto.HospitalOuterClass.Hospital)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.HospitalOuterClass.Hospital other) {
        if (other == proto.HospitalOuterClass.Hospital.getDefaultInstance()) return this;
        if (other.getTest() != 0) {
          setTest(other.getTest());
        }
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getTotalBeds() != 0) {
          setTotalBeds(other.getTotalBeds());
        }
        if (other.getAvailableBeds() != 0) {
          setAvailableBeds(other.getAvailableBeds());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.HospitalOuterClass.Hospital parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.HospitalOuterClass.Hospital) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int test_ ;
      /**
       * <code>int32 test = 1;</code>
       */
      public int getTest() {
        return test_;
      }
      /**
       * <code>int32 test = 1;</code>
       */
      public Builder setTest(int value) {
        
        test_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 test = 1;</code>
       */
      public Builder clearTest() {
        
        test_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object host_ = "";
      /**
       * <code>string host = 2;</code>
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string host = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string host = 2;</code>
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string host = 2;</code>
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>string host = 2;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 3;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 3;</code>
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 3;</code>
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 4;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 4;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 4;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 5;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 5;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 5;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 5;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 5;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int totalBeds_ ;
      /**
       * <code>int32 totalBeds = 6;</code>
       */
      public int getTotalBeds() {
        return totalBeds_;
      }
      /**
       * <code>int32 totalBeds = 6;</code>
       */
      public Builder setTotalBeds(int value) {
        
        totalBeds_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 totalBeds = 6;</code>
       */
      public Builder clearTotalBeds() {
        
        totalBeds_ = 0;
        onChanged();
        return this;
      }

      private int availableBeds_ ;
      /**
       * <code>int32 availableBeds = 7;</code>
       */
      public int getAvailableBeds() {
        return availableBeds_;
      }
      /**
       * <code>int32 availableBeds = 7;</code>
       */
      public Builder setAvailableBeds(int value) {
        
        availableBeds_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 availableBeds = 7;</code>
       */
      public Builder clearAvailableBeds() {
        
        availableBeds_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Hospital)
    }

    // @@protoc_insertion_point(class_scope:proto.Hospital)
    private static final proto.HospitalOuterClass.Hospital DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.HospitalOuterClass.Hospital();
    }

    public static proto.HospitalOuterClass.Hospital getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Hospital>
        PARSER = new com.google.protobuf.AbstractParser<Hospital>() {
      @java.lang.Override
      public Hospital parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Hospital(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Hospital> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Hospital> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.HospitalOuterClass.Hospital getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HospitalsForRegionReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.HospitalsForRegionReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto.Hospital hospital = 1;</code>
     */
    java.util.List<proto.HospitalOuterClass.Hospital> 
        getHospitalList();
    /**
     * <code>repeated .proto.Hospital hospital = 1;</code>
     */
    proto.HospitalOuterClass.Hospital getHospital(int index);
    /**
     * <code>repeated .proto.Hospital hospital = 1;</code>
     */
    int getHospitalCount();
    /**
     * <code>repeated .proto.Hospital hospital = 1;</code>
     */
    java.util.List<? extends proto.HospitalOuterClass.HospitalOrBuilder> 
        getHospitalOrBuilderList();
    /**
     * <code>repeated .proto.Hospital hospital = 1;</code>
     */
    proto.HospitalOuterClass.HospitalOrBuilder getHospitalOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.HospitalsForRegionReply}
   */
  public  static final class HospitalsForRegionReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.HospitalsForRegionReply)
      HospitalsForRegionReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HospitalsForRegionReply.newBuilder() to construct.
    private HospitalsForRegionReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HospitalsForRegionReply() {
      hospital_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HospitalsForRegionReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                hospital_ = new java.util.ArrayList<proto.HospitalOuterClass.Hospital>();
                mutable_bitField0_ |= 0x00000001;
              }
              hospital_.add(
                  input.readMessage(proto.HospitalOuterClass.Hospital.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          hospital_ = java.util.Collections.unmodifiableList(hospital_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.HospitalOuterClass.internal_static_proto_HospitalsForRegionReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.HospitalOuterClass.internal_static_proto_HospitalsForRegionReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.HospitalOuterClass.HospitalsForRegionReply.class, proto.HospitalOuterClass.HospitalsForRegionReply.Builder.class);
    }

    public static final int HOSPITAL_FIELD_NUMBER = 1;
    private java.util.List<proto.HospitalOuterClass.Hospital> hospital_;
    /**
     * <code>repeated .proto.Hospital hospital = 1;</code>
     */
    public java.util.List<proto.HospitalOuterClass.Hospital> getHospitalList() {
      return hospital_;
    }
    /**
     * <code>repeated .proto.Hospital hospital = 1;</code>
     */
    public java.util.List<? extends proto.HospitalOuterClass.HospitalOrBuilder> 
        getHospitalOrBuilderList() {
      return hospital_;
    }
    /**
     * <code>repeated .proto.Hospital hospital = 1;</code>
     */
    public int getHospitalCount() {
      return hospital_.size();
    }
    /**
     * <code>repeated .proto.Hospital hospital = 1;</code>
     */
    public proto.HospitalOuterClass.Hospital getHospital(int index) {
      return hospital_.get(index);
    }
    /**
     * <code>repeated .proto.Hospital hospital = 1;</code>
     */
    public proto.HospitalOuterClass.HospitalOrBuilder getHospitalOrBuilder(
        int index) {
      return hospital_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < hospital_.size(); i++) {
        output.writeMessage(1, hospital_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < hospital_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, hospital_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.HospitalOuterClass.HospitalsForRegionReply)) {
        return super.equals(obj);
      }
      proto.HospitalOuterClass.HospitalsForRegionReply other = (proto.HospitalOuterClass.HospitalsForRegionReply) obj;

      boolean result = true;
      result = result && getHospitalList()
          .equals(other.getHospitalList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getHospitalCount() > 0) {
        hash = (37 * hash) + HOSPITAL_FIELD_NUMBER;
        hash = (53 * hash) + getHospitalList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.HospitalOuterClass.HospitalsForRegionReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HospitalOuterClass.HospitalsForRegionReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HospitalOuterClass.HospitalsForRegionReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HospitalOuterClass.HospitalsForRegionReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HospitalOuterClass.HospitalsForRegionReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HospitalOuterClass.HospitalsForRegionReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HospitalOuterClass.HospitalsForRegionReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.HospitalOuterClass.HospitalsForRegionReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.HospitalOuterClass.HospitalsForRegionReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.HospitalOuterClass.HospitalsForRegionReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.HospitalOuterClass.HospitalsForRegionReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.HospitalOuterClass.HospitalsForRegionReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.HospitalOuterClass.HospitalsForRegionReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.HospitalsForRegionReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.HospitalsForRegionReply)
        proto.HospitalOuterClass.HospitalsForRegionReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.HospitalOuterClass.internal_static_proto_HospitalsForRegionReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.HospitalOuterClass.internal_static_proto_HospitalsForRegionReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.HospitalOuterClass.HospitalsForRegionReply.class, proto.HospitalOuterClass.HospitalsForRegionReply.Builder.class);
      }

      // Construct using proto.HospitalOuterClass.HospitalsForRegionReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHospitalFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (hospitalBuilder_ == null) {
          hospital_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          hospitalBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.HospitalOuterClass.internal_static_proto_HospitalsForRegionReply_descriptor;
      }

      @java.lang.Override
      public proto.HospitalOuterClass.HospitalsForRegionReply getDefaultInstanceForType() {
        return proto.HospitalOuterClass.HospitalsForRegionReply.getDefaultInstance();
      }

      @java.lang.Override
      public proto.HospitalOuterClass.HospitalsForRegionReply build() {
        proto.HospitalOuterClass.HospitalsForRegionReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.HospitalOuterClass.HospitalsForRegionReply buildPartial() {
        proto.HospitalOuterClass.HospitalsForRegionReply result = new proto.HospitalOuterClass.HospitalsForRegionReply(this);
        int from_bitField0_ = bitField0_;
        if (hospitalBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            hospital_ = java.util.Collections.unmodifiableList(hospital_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.hospital_ = hospital_;
        } else {
          result.hospital_ = hospitalBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.HospitalOuterClass.HospitalsForRegionReply) {
          return mergeFrom((proto.HospitalOuterClass.HospitalsForRegionReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.HospitalOuterClass.HospitalsForRegionReply other) {
        if (other == proto.HospitalOuterClass.HospitalsForRegionReply.getDefaultInstance()) return this;
        if (hospitalBuilder_ == null) {
          if (!other.hospital_.isEmpty()) {
            if (hospital_.isEmpty()) {
              hospital_ = other.hospital_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHospitalIsMutable();
              hospital_.addAll(other.hospital_);
            }
            onChanged();
          }
        } else {
          if (!other.hospital_.isEmpty()) {
            if (hospitalBuilder_.isEmpty()) {
              hospitalBuilder_.dispose();
              hospitalBuilder_ = null;
              hospital_ = other.hospital_;
              bitField0_ = (bitField0_ & ~0x00000001);
              hospitalBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getHospitalFieldBuilder() : null;
            } else {
              hospitalBuilder_.addAllMessages(other.hospital_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.HospitalOuterClass.HospitalsForRegionReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.HospitalOuterClass.HospitalsForRegionReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<proto.HospitalOuterClass.Hospital> hospital_ =
        java.util.Collections.emptyList();
      private void ensureHospitalIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          hospital_ = new java.util.ArrayList<proto.HospitalOuterClass.Hospital>(hospital_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.HospitalOuterClass.Hospital, proto.HospitalOuterClass.Hospital.Builder, proto.HospitalOuterClass.HospitalOrBuilder> hospitalBuilder_;

      /**
       * <code>repeated .proto.Hospital hospital = 1;</code>
       */
      public java.util.List<proto.HospitalOuterClass.Hospital> getHospitalList() {
        if (hospitalBuilder_ == null) {
          return java.util.Collections.unmodifiableList(hospital_);
        } else {
          return hospitalBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.Hospital hospital = 1;</code>
       */
      public int getHospitalCount() {
        if (hospitalBuilder_ == null) {
          return hospital_.size();
        } else {
          return hospitalBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.Hospital hospital = 1;</code>
       */
      public proto.HospitalOuterClass.Hospital getHospital(int index) {
        if (hospitalBuilder_ == null) {
          return hospital_.get(index);
        } else {
          return hospitalBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.Hospital hospital = 1;</code>
       */
      public Builder setHospital(
          int index, proto.HospitalOuterClass.Hospital value) {
        if (hospitalBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHospitalIsMutable();
          hospital_.set(index, value);
          onChanged();
        } else {
          hospitalBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Hospital hospital = 1;</code>
       */
      public Builder setHospital(
          int index, proto.HospitalOuterClass.Hospital.Builder builderForValue) {
        if (hospitalBuilder_ == null) {
          ensureHospitalIsMutable();
          hospital_.set(index, builderForValue.build());
          onChanged();
        } else {
          hospitalBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Hospital hospital = 1;</code>
       */
      public Builder addHospital(proto.HospitalOuterClass.Hospital value) {
        if (hospitalBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHospitalIsMutable();
          hospital_.add(value);
          onChanged();
        } else {
          hospitalBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Hospital hospital = 1;</code>
       */
      public Builder addHospital(
          int index, proto.HospitalOuterClass.Hospital value) {
        if (hospitalBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHospitalIsMutable();
          hospital_.add(index, value);
          onChanged();
        } else {
          hospitalBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Hospital hospital = 1;</code>
       */
      public Builder addHospital(
          proto.HospitalOuterClass.Hospital.Builder builderForValue) {
        if (hospitalBuilder_ == null) {
          ensureHospitalIsMutable();
          hospital_.add(builderForValue.build());
          onChanged();
        } else {
          hospitalBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Hospital hospital = 1;</code>
       */
      public Builder addHospital(
          int index, proto.HospitalOuterClass.Hospital.Builder builderForValue) {
        if (hospitalBuilder_ == null) {
          ensureHospitalIsMutable();
          hospital_.add(index, builderForValue.build());
          onChanged();
        } else {
          hospitalBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Hospital hospital = 1;</code>
       */
      public Builder addAllHospital(
          java.lang.Iterable<? extends proto.HospitalOuterClass.Hospital> values) {
        if (hospitalBuilder_ == null) {
          ensureHospitalIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, hospital_);
          onChanged();
        } else {
          hospitalBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Hospital hospital = 1;</code>
       */
      public Builder clearHospital() {
        if (hospitalBuilder_ == null) {
          hospital_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          hospitalBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.Hospital hospital = 1;</code>
       */
      public Builder removeHospital(int index) {
        if (hospitalBuilder_ == null) {
          ensureHospitalIsMutable();
          hospital_.remove(index);
          onChanged();
        } else {
          hospitalBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Hospital hospital = 1;</code>
       */
      public proto.HospitalOuterClass.Hospital.Builder getHospitalBuilder(
          int index) {
        return getHospitalFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.Hospital hospital = 1;</code>
       */
      public proto.HospitalOuterClass.HospitalOrBuilder getHospitalOrBuilder(
          int index) {
        if (hospitalBuilder_ == null) {
          return hospital_.get(index);  } else {
          return hospitalBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.Hospital hospital = 1;</code>
       */
      public java.util.List<? extends proto.HospitalOuterClass.HospitalOrBuilder> 
           getHospitalOrBuilderList() {
        if (hospitalBuilder_ != null) {
          return hospitalBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(hospital_);
        }
      }
      /**
       * <code>repeated .proto.Hospital hospital = 1;</code>
       */
      public proto.HospitalOuterClass.Hospital.Builder addHospitalBuilder() {
        return getHospitalFieldBuilder().addBuilder(
            proto.HospitalOuterClass.Hospital.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Hospital hospital = 1;</code>
       */
      public proto.HospitalOuterClass.Hospital.Builder addHospitalBuilder(
          int index) {
        return getHospitalFieldBuilder().addBuilder(
            index, proto.HospitalOuterClass.Hospital.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Hospital hospital = 1;</code>
       */
      public java.util.List<proto.HospitalOuterClass.Hospital.Builder> 
           getHospitalBuilderList() {
        return getHospitalFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.HospitalOuterClass.Hospital, proto.HospitalOuterClass.Hospital.Builder, proto.HospitalOuterClass.HospitalOrBuilder> 
          getHospitalFieldBuilder() {
        if (hospitalBuilder_ == null) {
          hospitalBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.HospitalOuterClass.Hospital, proto.HospitalOuterClass.Hospital.Builder, proto.HospitalOuterClass.HospitalOrBuilder>(
                  hospital_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          hospital_ = null;
        }
        return hospitalBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.HospitalsForRegionReply)
    }

    // @@protoc_insertion_point(class_scope:proto.HospitalsForRegionReply)
    private static final proto.HospitalOuterClass.HospitalsForRegionReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.HospitalOuterClass.HospitalsForRegionReply();
    }

    public static proto.HospitalOuterClass.HospitalsForRegionReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HospitalsForRegionReply>
        PARSER = new com.google.protobuf.AbstractParser<HospitalsForRegionReply>() {
      @java.lang.Override
      public HospitalsForRegionReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HospitalsForRegionReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HospitalsForRegionReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HospitalsForRegionReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.HospitalOuterClass.HospitalsForRegionReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Empty_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_AvailableBedsReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_AvailableBedsReply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Hospital_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Hospital_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_HospitalsForRegionReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_HospitalsForRegionReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Hospital.proto\022\005proto\"\007\n\005Empty\"%\n\022Avai" +
      "lableBedsReply\022\017\n\007message\030\001 \001(\005\"x\n\010Hospi" +
      "tal\022\014\n\004test\030\001 \001(\005\022\014\n\004host\030\002 \001(\t\022\014\n\004port\030" +
      "\003 \001(\005\022\n\n\002id\030\004 \001(\005\022\014\n\004name\030\005 \001(\t\022\021\n\ttotal" +
      "Beds\030\006 \001(\005\022\025\n\ravailableBeds\030\007 \001(\005\"<\n\027Hos" +
      "pitalsForRegionReply\022!\n\010hospital\030\001 \003(\0132\017" +
      ".proto.Hospital2\234\001\n\017HospitalService\022=\n\020g" +
      "etAvailableBeds\022\014.proto.Empty\032\031.proto.Av" +
      "ailableBedsReply\"\000\022J\n\025getHospitalsForReg" +
      "ion\022\017.proto.Hospital\032\036.proto.HospitalsFo" +
      "rRegionReply\"\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_proto_AvailableBedsReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_AvailableBedsReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_AvailableBedsReply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_proto_Hospital_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_Hospital_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Hospital_descriptor,
        new java.lang.String[] { "Test", "Host", "Port", "Id", "Name", "TotalBeds", "AvailableBeds", });
    internal_static_proto_HospitalsForRegionReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_HospitalsForRegionReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_HospitalsForRegionReply_descriptor,
        new java.lang.String[] { "Hospital", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
